services:
  mysql:
    image: mysql:8.0
    container_name: dbsec-mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
